// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Domain.DbEntities
{
    public partial class PriorityLevel
    {
        public PriorityLevel()
        {
            Tasks = new HashSet<Tasks>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string DisplayName { get; set; }
        [StringLength(200)]
        public string Description { get; set; }

        [InverseProperty("Priority")]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}