// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Core.Domain.DbEntities
{
    public partial class Project
    {
        public Project()
        {
            Sections = new HashSet<Sections>();
            Tasks = new HashSet<Tasks>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(250)]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedAt { get; set; }
        public bool Deleted { get; set; }

        [InverseProperty("Project")]
        public virtual ICollection<Sections> Sections { get; set; }
        [InverseProperty("Project")]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}